### ISSUE TITLE
Если бы не Соул, sirAgil, grandlegion и многие другие

### ISSUE THREAD

**Issue by makhotkin** [knelse/SphereEmu#2]
> Если бы не Соул, sirAgil, grandlegion и многие другие, мне бы никогда не пришло в голову, что этот проект вообще возможен. Огромное вам спасибо за работу и комьюнити! (Где бы результаты этой работы достать теперь…)

Пожалуйста.
https://sphere-k2.herokuapp.com/
https://github.com/makhotkin/Sphere_K2

**Comment by knelse** [comment]
Круто, спасибо!
Увидел формулу экспы - обрадовался. Думал уже табличку собирать :)
Теперь бы еще найти кого-нибудь живого, кто форматы .lnd (и вообще геометрии) ковырял

**Comment by makhotkin** [comment]
Нет, геометрию я точно не изучал. Скрипты ковырять пытался (там же целая виртуальная машина на клиенте, которая исполняет *.mbc скрипты), но счёл это направление бесперспективным. Понятно, что были разобраны все предметы и штрафы за мутатор не по уровню, иначе как бы состоялась кукла? А алгоритм распаковки конфигов мне подсказали добрые анонимусы (тк до этого я инжектил свою dll в клиент и вызывал метод распаковки, передавая управление на известный адрес)

Ещё была "спутниковая карта", и там были просто собраны все текстуры - не помню откуда. Трехмерной карты (хотя бы карты высот) нет, и не слышали.

К слову, сайт на хероку 28 ноября отключится (там платформа закрывает бесплатный тариф)

**Comment by makhotkin** [comment]
И ещё: моё уважение за реверсинг протокола. Это была какая-то недостижимая мечта тогда - свой сервер сделать ))

**Comment by knelse** [comment]
> Нет, геометрию я точно не изучал. Скрипты ковырять пытался (там же целая виртуальная машина на клиенте, которая исполняет *.mbc скрипты), но счёл это направление бесперспективным. Понятно, что были разобраны все предметы и штрафы за мутатор не по уровню, иначе как бы состоялась кукла? А алгоритм распаковки конфигов мне подсказали добрые анонимусы (тк до этого я инжектил свою dll в клиент и вызывал метод распаковки, передавая управление на известный адрес)
> 
> Ещё была "спутниковая карта", и там были просто собраны все текстуры - не помню откуда. Трехмерной карты (хотя бы карты высот) нет, и не слышали.
> 
> К слову, сайт на хероку 28 ноября отключится (там платформа закрывает бесплатный тариф)

Я нашел на гитхабе репу, где были написанные .mbc скрипты для чего-то другого, но так и не откопал код декомпилятора под них :) Помнится, Соул на форуме выкладывал, но я был слишком туп, чтобы все это себе сохранить куда-нибудь.

Про модификаторы понятно, да. Мне еще предстоит это писать, пока что я пытаюсь разобраться, что за фигня со шмотом происходит.

Спасибо, что про сайт сказал - подниму где-нибудь себе локальную версию, наверно)

**Comment by knelse** [comment]
> И ещё: моё уважение за реверсинг протокола. Это была какая-то недостижимая мечта тогда - свой сервер сделать ))

У меня есть серьезное подозрение, что они порядком упростили весь протокол, когда переписывали с DirectPlay на голый TCP. Я думал, это будет самая сложная часть (особенно учитывая, что я совершенно нифига не понимаю в реверсе), но я больше времени потратил на попытки убиться об стену, когда забыл в массиве масок 1 байт, чем на весь код вместе взятый

Если тебе внезапно интересно, у меня есть еще куча вещей, которые надо ковырять/писать ;)

**Comment by makhotkin** [comment]
> Я нашел на гитхабе репу, где были написанные .mbc скрипты для чего-то другого, но так и не откопал код декомпилятора под них :) Помнится, Соул на форуме выкладывал, но я был слишком туп, чтобы все это себе сохранить куда-нибудь.

Я не помню какого-то существенного декомпилятора, либо там было всего 5-10 опкодов. Может кто другой написал больше... но не знаю, не помню. Там много чего ещё могло произойти, после того как я потерял интерес к проекту.
Да, тебе бы grandlegion'а найти! 

Что касается "нашел на гитхабе репу, где были написанные .mbc скрипты": эти скрипты — домашная разработка Никиты, их Ростовского офиса, что писал Сферу и потом на том же движке Дом 3.

> Про модификаторы понятно, да. Мне еще предстоит это писать, пока что я пытаюсь разобраться, что за фигня со шмотом происходит.

Это как? Сервер не может одеть персонажа и отдать пакет с новыми статами?

> Спасибо, что про сайт сказал - подниму где-нибудь себе локальную версию, наверно)

На гитхабе кукла-2 в любом случае останется. Там бэкэнд всё равно не дописан... и кто писать будет, а главное зачем?
Ещё оказывается её кто-то обновил и выложил у себя: https://sphere-help.ru/sphere/

> У меня есть серьезное подозрение, что они порядком упростили весь протокол, когда переписывали с DirectPlay на голый TCP. Я думал, это будет самая сложная часть (особенно учитывая, что я совершенно нифига не понимаю в реверсе), но я больше времени потратил на попытки убиться об стену, когда забыл в массиве масок 1 байт, чем на весь код вместе взятый

Я посмотрел в статьи на хабре примеры пакетов - там такая куча не понятно зачем нужных полей, что берут сомнения.
Сейчас часто приложения друг другу протобафы шлют, и их пакеты (если не шифрованы или шифр снят) разобрать можно, даже не зная какое поле как называется... А в сфере, по всей видимости, колхоз, по старой доброй памяти.

> Если тебе внезапно интересно, у меня есть еще куча вещей, которые надо ковырять/писать ;)

Не, спасибо. Сейчас и работы хватает, и интереса к Сфере нет.

**Comment by knelse** [comment]
> > Я нашел на гитхабе репу, где были написанные .mbc скрипты для чего-то другого, но так и не откопал код декомпилятора под них :) Помнится, Соул на форуме выкладывал, но я был слишком туп, чтобы все это себе сохранить куда-нибудь.
> 
> Я не помню какого-то существенного декомпилятора, либо там было всего 5-10 опкодов. Может кто другой написал больше... но не знаю, не помню. Там много чего ещё могло произойти, после того как я потерял интерес к проекту. Да, тебе бы grandlegion'а найти!
> Что касается "нашел на гитхабе репу, где были написанные .mbc скрипты": эти скрипты — домашная разработка Никиты, их Ростовского офиса, что писал Сферу и потом на том же движке Дом 3.

Там было что-то вообще стороннее, похожее на студенческий проект, но при этом похоже по виду скомпилированных файлов. Grandlegion бы помог, да :)

> > Про модификаторы понятно, да. Мне еще предстоит это писать, пока что я пытаюсь разобраться, что за фигня со шмотом происходит.
> 
> Это как? Сервер не может одеть персонажа и отдать пакет с новыми статами?

Не, размер пакета / сегмента в пакете зависит от типа айтема и от его суффикса, вот например:

1, кресты 7	
02.11.2022 13:11:38			28002C0100	D8EF	8EE2	A08F	0F80842E090000000000000000409145	A64512	1560	80521C	A0C0020100
1, шлем 9 на 90										
02.11.2022 13:30:54			2B002C0100	FC0A	06FB	D48B	0F80842E090000000000000000409145	A61613	1560	C05D1F	A0900500FFFFFFFF
IV арбалет сияния 85/5 14800 вес		
26/08/2022 20:44:48			2C002C0100	A477	A098	D887	0F80842E090000000000000000409145	66BC23	4801	061E31	010A5900F0FFFFFF0F
1, -прана 9 х13										
02.11.2022 13:30:00			30002C0100	B809	B5F8	1487	0F80842E090000000000000000409145	26B810	1560	80161F	A0900500FFFFFFFF0516680000
1, кольцо воздуха на 34 титул									
02.11.2022 14:01:22			3C002C0100	E035	A451	E08B	0F80842E090000000000000000409145	26FCA3	4701	0644A3	000A5900F0FFFFFF5F7807B5BB2FB2B4B036B934B7B3	981A	00

С учетом того, что сдвиги там не на целое число байт, я пока не написал рабочий код, который разбирает пакет с произвольным количеством айтемов. Более-менее терпимые версии у меня есть под 1 айтем и под 2, но не всех видов, дальше я пока сломался и пытаюсь найти границы полей. Насколько я понимаю, предметы и мобов/NPC/прочие объекты сервер энкодит одинаково, т.е. когда разберусь с этим, можно будет честно стырить с лайва весь контент игрового мира, если по нему долго побегать туда-сюда.

> > Спасибо, что про сайт сказал - подниму где-нибудь себе локальную версию, наверно)
> 
> На гитхабе кукла-2 в любом случае останется. Там бэкэнд всё равно не дописан... и кто писать будет, а главное зачем? Ещё оказывается её кто-то обновил и выложил у себя: https://sphere-help.ru/sphere/

О, отлично.

> > У меня есть серьезное подозрение, что они порядком упростили весь протокол, когда переписывали с DirectPlay на голый TCP. Я думал, это будет самая сложная часть (особенно учитывая, что я совершенно нифига не понимаю в реверсе), но я больше времени потратил на попытки убиться об стену, когда забыл в массиве масок 1 байт, чем на весь код вместе взятый
> 
> Я посмотрел в статьи на хабре примеры пакетов - там такая куча не понятно зачем нужных полей, что берут сомнения. Сейчас часто приложения друг другу протобафы шлют, и их пакеты (если не шифрованы или шифр снят) разобрать можно, даже не зная какое поле как называется... А в сфере, по всей видимости, колхоз, по старой доброй памяти.

Там явно дофига легаси и странного, да, но помнится когда я давным давно смотрел посты grandlegion'а про протокол Сферы (еще на DirectPlay), они были устроены сложнее, чем что я вижу сейчас. Возможно, дело в разнице в Х лет работы погромистом.

> > Если тебе внезапно интересно, у меня есть еще куча вещей, которые надо ковырять/писать ;)
> 
> Не, спасибо. Сейчас и работы хватает, и интереса к Сфере нет.

Попытка не пытка :)
